#!/usr/bin/env bash
#
# Run artisan inside the sandbox application.
#
#   ./dev migrate
#   ./dev isproject:crud Product
#   ./dev isproject:crud-all --force
#
# Anything that is not an artisan command still works through:
#   docker compose exec -w /var/www/sandbox app <command>

exec docker compose exec -w /var/www/sandbox app php artisan "$@"
