<?php

namespace IsProject\Framework\Support;

use Illuminate\Routing\Route as RoutingRoute;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;
use IsProject\Framework\Models\Permission;

/**
 * Discovers what there is to permit by reading the application's own routes.
 *
 * Nothing is declared by hand. A permission is one named route, which means a
 * module generated by `isproject:crud` brings its permissions with it — the
 * point of wiring RBAC into a framework that also generates the routes.
 *
 * Only *named* routes can be permitted: the enforcement middleware identifies
 * the current request by route name, so an unnamed route has nothing to match
 * against. Every route the generator writes is named.
 */
class PermissionRegistry
{
    /** Verbs that read rather than change, shown first in the matrix. */
    private const ABILITY_ORDER = [
        'index', 'show', 'report', 'export', 'create', 'store', 'edit', 'update', 'destroy',
    ];

    /** Wording that reads as an action, not as a controller method name. */
    private const ABILITY_LABELS = [
        'index' => 'List',
        'show' => 'View',
        'create' => 'Add form',
        'store' => 'Create',
        'edit' => 'Edit form',
        'update' => 'Update',
        'destroy' => 'Delete',
        'report' => 'Report',
        'export' => 'Export',
    ];

    /** @var array<int, array<string, mixed>>|null */
    private ?array $modules = null;

    /**
     * Every permissible route, grouped into modules for the assignment matrix.
     *
     * @return array<int, array{key: string, label: string, abilities: array<string, array{name: string, label: string, uri: string, methods: string}>}>
     */
    public function modules(): array
    {
        if ($this->modules !== null) {
            return $this->modules;
        }

        $modules = [];

        foreach ($this->routes() as $route) {
            $name = (string) $route->getName();
            [$module, $ability] = $this->split($name);

            $modules[$module]['key'] = $module;
            $modules[$module]['label'] = $this->moduleLabel($module);
            $modules[$module]['abilities'][$ability] = [
                'name' => $name,
                'label' => self::ABILITY_LABELS[$ability] ?? Str::headline($ability),
                'uri' => '/'.ltrim($route->uri(), '/'),
                'methods' => implode('|', array_diff($route->methods(), ['HEAD'])),
            ];
        }

        foreach ($modules as $key => $module) {
            $modules[$key]['abilities'] = $this->sortAbilities($module['abilities']);
        }

        ksort($modules);

        return $this->modules = array_values($modules);
    }

    /**
     * Column headings for the matrix: every ability any module has, in a
     * reading order rather than the order they happened to be discovered.
     *
     * @return array<int, string>
     */
    public function abilityColumns(): array
    {
        $found = [];

        foreach ($this->modules() as $module) {
            foreach (array_keys($module['abilities']) as $ability) {
                $found[$ability] = true;
            }
        }

        return array_keys($this->sortAbilities($found));
    }

    /**
     * Route names that may be permitted, flat.
     *
     * @return array<int, string>
     */
    public function names(): array
    {
        $names = [];

        foreach ($this->modules() as $module) {
            foreach ($module['abilities'] as $ability) {
                $names[] = $ability['name'];
            }
        }

        return $names;
    }

    /**
     * Bring the permissions table in line with the routes that exist now.
     *
     * Removing orphans matters: a route deleted from the application should
     * not leave a permission that roles can still be granted. The pivot rows
     * go with it through the cascade on the foreign key.
     *
     * @return array{added: array<int, string>, removed: array<int, string>}
     */
    public function sync(): array
    {
        $discovered = $this->names();
        $existing = Permission::query()->pluck('name')->all();

        $added = array_values(array_diff($discovered, $existing));
        $removed = array_values(array_diff($existing, $discovered));

        if ($added !== []) {
            $now = now();

            Permission::query()->insert(array_map(
                fn (string $name) => ['name' => $name, 'created_at' => $now, 'updated_at' => $now],
                $added,
            ));
        }

        if ($removed !== []) {
            Permission::query()->whereIn('name', $removed)->delete();
        }

        if ($added !== [] || $removed !== []) {
            Access::flush();
        }

        return ['added' => $added, 'removed' => $removed];
    }

    /**
     * Routes discovered but never synced. Shown on the roles screen, because a
     * permission that is not in the table cannot be assigned to anyone.
     *
     * @return array<int, string>
     */
    public function unsynced(): array
    {
        return array_values(array_diff($this->names(), Permission::query()->pluck('name')->all()));
    }

    /**
     * The routes worth offering. Anything without a name cannot be enforced,
     * and the ignore list keeps framework and tooling routes out of a matrix
     * a lecturer has to read.
     *
     * @return array<int, RoutingRoute>
     */
    private function routes(): array
    {
        $ignored = (array) config('isproject.access.ignored_routes', []);
        $seen = [];
        $routes = [];

        foreach (Route::getRoutes() as $route) {
            $name = $route->getName();

            if (! $name || isset($seen[$name])) {
                continue;
            }

            if ($this->matchesAny($name, $ignored)) {
                continue;
            }

            $seen[$name] = true;
            $routes[] = $route;
        }

        return $routes;
    }

    /** @param  array<int, string>  $patterns */
    private function matchesAny(string $name, array $patterns): bool
    {
        foreach ($patterns as $pattern) {
            if (Str::is($pattern, $name)) {
                return true;
            }
        }

        return false;
    }

    /**
     * "products.index" splits into module "products" and ability "index";
     * "isproject.settings.index" keeps "isproject.settings" as the module, so
     * a namespaced module is not shredded into its parts.
     *
     * @return array{0: string, 1: string}
     */
    private function split(string $name): array
    {
        if (! str_contains($name, '.')) {
            // A standalone route such as "login" is its own module, so it can
            // still be granted rather than being silently unreachable.
            return [$name, 'access'];
        }

        return [Str::beforeLast($name, '.'), Str::afterLast($name, '.')];
    }

    /**
     * "products" reads as "Products"; this package's own "isproject.roles"
     * reads as "Roles" rather than "Isproject Roles". The full key is printed
     * under the label in the matrix, so dropping the prefix loses nothing even
     * when an application has a "roles" module of its own.
     */
    private function moduleLabel(string $module): string
    {
        return Str::headline(str_replace('.', ' ', Str::after($module, 'isproject.')));
    }

    /**
     * @param  array<string, mixed>  $abilities
     * @return array<string, mixed>
     */
    private function sortAbilities(array $abilities): array
    {
        uksort($abilities, function (string $a, string $b) {
            $ia = array_search($a, self::ABILITY_ORDER, true);
            $ib = array_search($b, self::ABILITY_ORDER, true);

            // Anything not in the known list sorts after what is, alphabetically
            // among itself, so a custom action lands predictably.
            return match (true) {
                $ia !== false && $ib !== false => $ia <=> $ib,
                $ia !== false => -1,
                $ib !== false => 1,
                default => strcmp($a, $b),
            };
        });

        return $abilities;
    }
}
